##################################################################
#              Docker Compose file that starts sapspa master               #
##################################################################
version: '3.5'

services:
  consul:
    image: consul
    network_mode: "host"
    ports:
      - 23340
      - 23342
      - 23341
      - 23346
      - 23345
    command:
      consul agent -data-dir=consuldata -ui -client=0.0.0.0 -bind=0.0.0.0 -join=${MASTER_IP} -dns-port=23346 -http-port=23345 -retry-join "[::1]:23341" -serf-wan-port=23342

  node_exporter:
    image: prom/node-exporter
    network_mode: "host"
    ports:
      - 23311
    command: /bin/node_exporter --web.listen-address=":23311"

  agent:
    build:
      context: ../src/agent
      args:
        - MASTER_IP=${MASTER_IP}
    restart: "yes"
    network_mode: "host"
    depends_on:
      - consul
    ports:
      - 23310
    expose:
      - 23310
    command:
      uwsgi --http 0.0.0.0:23310 --wsgi-file sapspa_agent.py --callable app_dispatch
    volumes:
      - ../src/agent:/opt/agent
      - /usr/sap:/usr/sap
      - /sapmnt:/sapmnt

  filebeat:
    build: elastic/filebeat:7.4.2
    restart: "yes"
    network_mode: "host"
    command:
      sed -i "s?localhost:23392?${MASTER_IP}:23392?g" /etc/filebeat/filebeat.yml && sed -i 's?index: "filebeat?index: "'`hostname`'-filebeat?g' /etc/filebeat/filebeat.yml && /usr/share/filebeat/filebeat -c /etc/filebeat/filebeat.yml
    volumes:
      - ../etc/filebeat:/etc/filebeat
      - /usr/sap:/usr/sap
      - /sapmnt:/sapmnt
